service: ecoleta-api

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  prune: # automatically prune old lambda versions
    automatic: true
    number: 3

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-prune-plugin

provider:
  name: aws
  runtime: nodejs12.x
  frameworkVersion: '1.64.1'
  stage: ${opt:stage, 'local'}
  region: ${opt:region, 'us-east-1'}
  apiGateway:
    minimumCompressionSize: 1024 *# Enable gzip compression for responses > 1 KB
  environment:
    DEBUG: '*'
    NODE_ENV: ${self:provider.stage}
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1


functions:
  hello:
    handler: src/handlers/users/get.handler
    events:
      - http:
          method: get
          path: /users
          cors: true
