name: Deploy Application
on:
  push:
    branches:
      - master
jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_API_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      NODE_ENV: prod
    
    steps:
    - uses: actions/checkout@v1
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: us-east-1
    - name: Install dependencies
      run: npm install
    - name: Deploy lambda
      run: npm run deploy